version: '3'
services:
  db:
    container_name: heal-e-database
    image: mysql
    restart: always
    env_file: ../.env

    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./heal_e_database_creation.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  mysql-data:
