apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-heale-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-heale
  template:
    metadata:
      labels:
        app: database-heale
    spec:
      containers:
      - name: database-heale
        image: ravailhe/mysqlcloud
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "heal_e_database"
        - name: MYSQL_USER
          value: "heal_e_user"
        - name: MYSQL_PASSWORD
          value: "user"
        - name: BACKEND_HOST
          value: "backend_heale"
        - name: BACKEND_PORT
          value: "3001"
        - name: FRONTEND_HOST
          value: "frontend_heale"
        - name: FRONTEND_PORT
          value: "3000"
