apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-heale-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-heale
  template:
    metadata:
      labels:
        app: frontend-heale
    spec:
      containers:
      - name: frontend-heale
        image: ravailhe/frontendcloud
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "heal_e_database"
        - name: MYSQL_USER
          value: "heal_e_user"
        - name: MYSQL_PASSWORD
          value: "user"
        - name: BACKEND_HOST
          value: "localhost"
        - name: BACKEND_PORT
          value: "3001"
        - name: FRONTEND_HOST
          value: "localhost"
        - name: FRONTEND_PORT
          value: "3000"