apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-heale-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-heale
  template:
    metadata:
      labels:
        app: backend-heale
    spec:
      containers:
      - name: backend-heale
        image: ravailhe/backendcloud
        ports:
        - containerPort: 3001
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "heal_e_database"
        - name: MYSQL_USER
          value: "heal_e_user"
        - name: MYSQL_PASSWORD
          value: "user"
        - name: BACKEND_HOST
          value: "localhost"
        - name: BACKEND_PORT
          value: "3001"
        - name: FRONTEND_HOST
          value: "localhost"
        - name: FRONTEND_PORT
          value: "3000"
